export default {
  LOGIN: 'LOGIN', // 登录
  LOGOUT: 'LOGOUT', // 登出
  ADD_ACCOUNT: 'ADD_ACCOUNT', // 添加账号
  ADD_AUTHS: 'ADD_AUTHS', // 添加用户当前医院权限
  ADD_MODULE_LIST: 'ADD_MODULE_LIST', // 添加模块列表
  ADD_AUTH_STR_LIST: 'ADD_AUTH_STR_LIST', // 添加权限字符串
  ADD_VERIFY_CODE: 'ADD_VERIFY_CODE', // 添加图形验证码
  ADD_ORGANIZATION: 'ADD_ORGANIZATION', // 添加机构列表
  UPDATE_ORGANIZATION_INVITED: 'UPDATE_ORGANIZATION_INVITED', // 添加邀请机构
  HOSP_IN_ORG_LIST: 'HOSP_IN_ORG_LIST', // 获取用户所在机构下的医院信息
  ADD_SIDEBAR_LIST: 'ADD_SIDEBAR_LIST', // 添加侧边栏
  INIT_PAGE: 'INIT_PAGE', // 初始化页面,
  GET_FIRST_TAB: 'GET_FIRST_TAB',
  GET_USER_INFO: 'GET_USER_INFO',
  LOGIN_AC: 'LOGIN_AC',
  UPDATE_INVITATION_DATA: 'UPDATE_INVITATION_DATA', // 邀请数据
  TIMEOUT_PANEL: 'TIMEOUT_PANEL', // 超时登录面板
  SET_SOURCE_ID: 'SET_SOURCE_ID', // 存储sourceId,
  LOGOUTAC: 'LOGOUTAC',
  SET_GEETEST_CAPTCHA: 'SET_GEETEST_CAPTCHA',
  ADD_AUTH_Map: 'types.ADD_AUTH_Map',
  ROUTER_INFO_MAP: 'types.ROUTER_INFO_MAP'
};
